"""Regenerate the cross-language protocol vectors.

    uv run python subnet/protocol/tests/make_vectors.py

The vectors pin the byte-level contract every implementation must match: canonical
JSON, the blob format, attestation binding, the job AAD and the receipt message. The
same file is checked into the JS SDK (sdk/js/test/vectors.json); a test in the
development workspace asserts the two copies are identical.
"""

from __future__ import annotations

import json
from pathlib import Path

from kuno_protocol.attestation import enclave_id_for, gpu_nonce_for, report_data_for
from kuno_protocol.blobs import encrypt_blob
from kuno_protocol.canonical import b64e, canonical_json, sha256_hex
from kuno_protocol.profiles import InputRole, Mode
from kuno_protocol.receipts import ReceiptBody, VideoInfo, receipt_message
from kuno_protocol.schemas import GenerationParams, job_aad

HERE = Path(__file__).resolve().parent
COPIES = [HERE / "vectors.json", HERE.parents[2] / "sdk" / "js" / "test" / "vectors.json"]

KEY = bytes(range(32))
HPKE_PUBLIC = bytes(range(100, 132))
SIGNING_PUBLIC = bytes(range(200, 232))
NONCE = bytes(range(50, 82))
GPU_EVIDENCE = b"gpu evidence"


def build() -> dict:
    params = GenerationParams(
        profile_id="h3-turbo",
        mode=Mode.FIRST_LAST_FRAME,
        duration_s=5.0,
        resolution="768p",
        aspect_ratio="16:9",
        fps=24,
        audio=True,
        input_roles=[InputRole.FIRST_FRAME, InputRole.LAST_FRAME],
    )
    job_id = "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
    receipt_body = ReceiptBody(
        job_id=job_id,
        enclave_id="0" * 32,
        profile_id="h3-turbo",
        image_digest="sha256:example",
        params_digest=sha256_hex(canonical_json(params.model_dump(mode="json"))),
        input_digest="1" * 64,
        output_digest="2" * 64,
        output_bytes=1024,
        content_digest="3" * 64,
        attestation_digest="4" * 64,
        started_at=1_800_000_000.0,
        finished_at=1_800_000_042.5,
        gpu_seconds=170.0,
        video=VideoInfo(duration_s=5.166, width=1344, height=768, fps=24, frames=124, audio=True),
        miner_hotkey=None,
    )
    return {
        "note": "Generated by subnet/protocol/tests/make_vectors.py. Every implementation must reproduce these bytes.",
        "canonical_json": [
            {"value": {"b": 5.0, "a": [1.5, "é", None, True], "c": {"z": 1, "y": 2}},
             "encoded": canonical_json({"b": 5.0, "a": [1.5, "é", None, True], "c": {"z": 1, "y": 2}}).decode()},
            {"value": {"duration_s": 5.0, "fps": 24}, "encoded": canonical_json({"duration_s": 5.0, "fps": 24}).decode()},
            {"value": [], "encoded": "[]"},
        ],
        "blob": {
            "base_key_b64": b64e(KEY),
            "label": f"{job_id}/output/video",
            "plaintext_b64": b64e(bytes(range(256)) * 5),
            "chunk_size": 256,
            # Nonce prefixes are random, so implementations check by decrypting this ciphertext.
            "ciphertext_b64": b64e(encrypt_blob(KEY, f"{job_id}/output/video", bytes(range(256)) * 5, chunk_size=256)),
        },
        "attestation": {
            "nonce_hex": NONCE.hex(),
            "hpke_public_key_b64": b64e(HPKE_PUBLIC),
            "signing_public_key_b64": b64e(SIGNING_PUBLIC),
            "gpu_evidence_b64": b64e(GPU_EVIDENCE),
            "enclave_id": enclave_id_for(HPKE_PUBLIC, SIGNING_PUBLIC),
            "gpu_nonce_hex": gpu_nonce_for(NONCE, HPKE_PUBLIC, SIGNING_PUBLIC).hex(),
            "report_data_hex": report_data_for(NONCE, HPKE_PUBLIC, SIGNING_PUBLIC, GPU_EVIDENCE).hex(),
            "report_data_without_gpu_hex": report_data_for(NONCE, HPKE_PUBLIC, SIGNING_PUBLIC, None).hex(),
        },
        "job_aad": {
            "job_id": job_id,
            "enclave_id": "0" * 32,
            "params": params.model_dump(mode="json"),
            "input_blob_ids": ["a" * 32, "b" * 32],
            "encoded": job_aad(job_id, "0" * 32, params, ["a" * 32, "b" * 32]).decode(),
        },
        "receipt": {
            "body": receipt_body.model_dump(mode="json"),
            "message_b64": b64e(receipt_message(receipt_body)),
        },
    }


def main() -> None:
    text = json.dumps(build(), indent=2, ensure_ascii=False) + "\n"
    for path in COPIES:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
